/**
 * CooL × Contrast, end to end, in about ninety seconds and with no cluster.
 *
 *     node examples/contrast/demo.mjs
 *
 * It runs against `tests/fixtures/contrast-fixtures.json` — Coordinator
 * artefacts generated by Contrast's OWN code (see tools/contrast-fixture/). So
 * every certificate chain, every X.509 extension and every signature in this
 * demo is real. What is NOT real is the hardware: the TDX quote behind the
 * fixture certificates was constructed in software. The demo says so where it
 * matters, and the hardware path is in docs/contrast.md.
 *
 * Seven acts:
 *
 *   1  what Contrast says this workload is
 *   2  four AI changes, sealed inside it
 *   3  an independent verifier's verdict
 *   4  tamper with the change            → must fail
 *   5  steal another workload's identity → must fail
 *   6  a Coordinator nobody attested     → must fail
 *   7  the image is rebuilt              → must be visible
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { CooL } from "../../src/index.ts";
import { verifyEvidence } from "../../src/verify.ts";
import { ContrastWorkload, parseManifest } from "../../src/contrast/index.ts";
import {
  cleanupContrastPods,
  contrastPod,
  coordinatorRootCA,
  manifestBytes,
} from "../../tests/support/contrast-pod.ts";

// The fixture bundle stores certificates and keys as base64 DER; this writes
// one workload back out as the exact files Contrast's initializer creates.
const pods = new Map();
const pod = (name) => {
  if (!pods.has(name)) pods.set(name, contrastPod(name));
  return pods.get(name);
};

const genuineRoot = coordinatorRootCA("genuine");
const manifest = manifestBytes;

/* ── presentation ────────────────────────────────────────────────────── */

const W = 74;
const rule = (ch = "─") => console.log(ch.repeat(W));
const act = (n, title) => {
  console.log();
  rule();
  console.log(`  ${n}. ${title.toUpperCase()}`);
  rule();
};
const kv = (k, v) => console.log(`  ${String(k).padEnd(22)} ${v}`);
const PASS = "✓";
const FAIL = "✗";

function verdictLine(label, verdict) {
  const domains = ["binding", "signature", "inclusion", "workload"];
  const cells = domains
    .map((d) => `${d}=${verdict.checks[d].status}`)
    .join("  ");
  console.log(`  ${verdict.ok ? PASS : FAIL} ${label.padEnd(30)} ${cells}`);
  return verdict;
}

/** A deep, mutable copy — the forgeries below need to edit readonly fields. */
const clone = (value) => JSON.parse(JSON.stringify(value));

/** What an auditor passes in: their own pinned root, their own manifest. */
const audit = { coordinatorRootCA: genuineRoot, expectedManifest: manifest, requireHardware: true };

console.log();
console.log("  CooL × Edgeless Systems Contrast");
console.log("  confidential execution + independently verifiable AI-change evidence");

/* ── 1 · identity ────────────────────────────────────────────────────── */

act(1, "what Contrast says this workload is");

const runtime = await ContrastWorkload.open({ root: pod("ai-service"), manifest });
const id = runtime.identity;

kv("platform", `${id.platform} / ${id.tee}`);
kv("workload", id.workload_name);
kv("policy hash", id.policy_hash.slice(4));
kv("workload secret id", id.workload_secret_id);
kv("MRTD", id.registers.mrtd.slice(4, 44) + "…");
kv("RTMR3", id.registers.rtmr3.slice(4, 44) + "…");
kv("manifest digest", id.manifest_digest);
console.log();
console.log("  Every line above was read out of the Coordinator-issued mesh certificate");
console.log("  at /contrast/tls-config/certChain.pem — not out of configuration. The");
console.log("  policy hash is the key of this pod's entry in the Contrast manifest:");
const parsed = parseManifest(manifest);
const entry = parsed.policies[id.policy_hash.slice(4)];
kv("  manifest SANs", entry.sans.join(", "));
kv("  manifest secret id", entry.workloadSecretId);

/* ── 2 · changes ─────────────────────────────────────────────────────── */

act(2, "four AI changes, sealed inside the confidential workload");

const cool = new CooL({ applicationId: "refund-agent", runtime, logId: "refund-agent-prod" });
await cool.ready();
kv("signing key", Object.keys(cool.keyDirectory).join(", "));
console.log("  ↳ derived from the Contrast workload secret: not derivable outside this pod");
console.log();

const changes = [
  ["model", "billing/refund-agent#model", "refund-classifier@2", "refund-classifier@3", "ci:github-actions", "oidc"],
  ["prompt", "billing/refund-agent#system", "Refund when the policy allows.", "Refund when the policy allows. Escalate above $500.", "user:priya@bank.example", "session"],
  ["agent-permission", "billing/refund-agent#tools", "read:orders", "read:orders,write:refunds", "user:priya@bank.example", "session"],
  ["params", "billing/refund-agent#temperature", "0.2", "0.7", "ci:github-actions", "oidc"],
];

const receipts = [];
for (const [kind, ref, before, after, actorId, method] of changes) {
  const { evidence } = await cool.change({
    kind,
    ref,
    before,
    after,
    environment: "prod",
    actor: { id: actorId, method },
  });
  receipts.push(evidence);
  console.log(`  ${PASS} ${kind.padEnd(18)} ${ref.padEnd(36)} leaf ${evidence.inclusion.leaf_index}`);
}

const { evidence: execution } = await cool.record({
  type: "model.execution",
  metadata: { model: "refund-classifier@3", temperature: 0.7 },
  payloads: { input: "refund $420 for order 19both", output: "approved" },
});
receipts.push(execution);
console.log(`  ${PASS} ${"model.execution".padEnd(18)} ${"(prompt + answer committed, not stored)".padEnd(36)} leaf ${execution.inclusion.leaf_index}`);
console.log();
console.log(`  One transparency log, ${receipts.length} leaves: order and completeness are provable,`);
console.log("  so a record cannot be quietly removed from the middle of the history.");

await cool.close();

/* ── 3 · independent verification ────────────────────────────────────── */

act(3, "an independent verifier's verdict");

console.log("  Input: the receipts, plus two files the auditor obtained themselves with");
console.log("  `contrast verify -c <coordinator>`. No network, no cluster, no trust in us.");
console.log();
for (const receipt of receipts) {
  const label =
    receipt.record.schema === "cool.change.v2"
      ? `${receipt.record.change.kind}: ${receipt.record.change.ref.split("#")[1]}`
      : receipt.record.event.type;
  verdictLine(label, await verifyEvidence(receipt, audit));
}
const sample = await verifyEvidence(receipts[0], audit);
console.log();
console.log(`  workload domain: ${sample.checks.workload.detail}`);

/* ── 4 · tamper with the change ──────────────────────────────────────── */

act(4, "tamper with the AI change itself");

const tampered = clone(receipts[1]);
tampered.record.change.after_hash = tampered.record.change.after_hash.replace(/.$/, (ch) =>
  ch === "a" ? "b" : "a",
);
const t = verdictLine("edited prompt commitment", await verifyEvidence(tampered, audit));
console.log(`  ↳ ${t.reasons[0]}`);
console.log("  The workload credential is still genuine, and the verdict says so rather than");
console.log("  collapsing to 'invalid' — an auditor learns WHICH guarantee broke.");
console.log(`  workload domain still: ${t.checks.workload.status}`);

/* ── 5 · steal another workload's identity ───────────────────────────── */

act(5, "present this receipt as a different workload's");

const otherChain = readFileSync(join(pod("sidecar-service"), "tls-config", "certChain.pem"), "utf8");
const stolen = clone(receipts[0]);
stolen.attestation.workload.cert_chain = otherChain;
const s = verdictLine("sidecar-service credential", await verifyEvidence(stolen, audit));
console.log(`  ↳ ${s.checks.workload.detail}`);

const runtime2 = await ContrastWorkload.open({ root: pod("sidecar-service"), manifest });
const cool2 = new CooL({ applicationId: "sidecar", runtime: runtime2 });
const { evidence: theirs } = await cool2.record({ type: "model.execution", metadata: {} });
await cool2.close();

const both = clone(receipts[0]);
both.attestation.workload = clone(theirs.attestation.workload);
both.record.runtime.workload = clone(theirs.record.runtime.workload);
const b = verdictLine("credential AND sealed identity", await verifyEvidence(both, audit));
console.log(`  ↳ ${b.reasons[0]}`);
console.log();
console.log("  Both halves of the binding were replaced so they agree with each other.");
console.log("  The record signature covers the sealed identity, so making them agree");
console.log("  breaks the signature instead. There is no third thing to swap.");

/* ── 6 · a Coordinator nobody attested ──────────────────────────────── */

act(6, "a receipt from a Coordinator nobody attested");

const rogueRuntime = await ContrastWorkload.open({ root: pod("ai-service-rogue-coordinator") });
const rogueCool = new CooL({ applicationId: "refund-agent", runtime: rogueRuntime });
const { evidence: rogue } = await rogueCool.record({ type: "model.execution", metadata: {} });
await rogueCool.close();

verdictLine("against its own root", await verifyEvidence(rogue, { coordinatorRootCA: rogueRuntime.coordinatorRootCA }));
console.log("  ↳ internally perfect: real chain, real binding, real signatures.");
const r = verdictLine("against the attested root", await verifyEvidence(rogue, audit));
console.log(`  ↳ ${r.checks.workload.detail}`);
console.log();
console.log("  This is why the root must come from the reader's own `contrast verify`.");
console.log("  A root the pod hands you cannot establish the pod.");

/* ── 7 · the image is rebuilt ────────────────────────────────────────── */

act(7, "the image is rebuilt — redeployment is visible, not silent");

const approved = { mrtd: id.registers.mrtd.slice(4) };
verdictLine("approved image", await verifyEvidence(receipts[0], { ...audit, expectedRegisters: approved }));

const upgradedRuntime = await ContrastWorkload.open({ root: pod("upgraded-ai-service"), manifest });
const upgradedCool = new CooL({ applicationId: "refund-agent", runtime: upgradedRuntime });
const { evidence: upgraded } = await upgradedCool.record({ type: "model.execution", metadata: {} });
await upgradedCool.close();

const u = verdictLine("rebuilt image, same policy", await verifyEvidence(upgraded, { ...audit, expectedRegisters: approved }));
console.log(`  ↳ ${u.checks.workload.detail}`);
console.log();
console.log("  Same manifest entry, same policy hash, different MRTD. The pin catches it.");
console.log("  And the old receipts keep verifying — an upgrade does not retroactively");
console.log("  invalidate history, which is what makes the trail usable in an audit.");

/* ── close ───────────────────────────────────────────────────────────── */

console.log();
rule("═");
console.log("  Contrast proves the workload was confidential and attestable.");
console.log("  CooL proves what changed inside it, and binds that evidence to the workload.");
console.log();
console.log("  Not claimed: that any hardware was involved here. These fixtures carry a");
console.log("  software-built TDX quote. On real TDX/SEV-SNP the same code path runs with");
console.log("  the Coordinator having actually checked Intel DCAP — see docs/contrast.md.");
rule("═");
console.log();

cleanupContrastPods();
