/**
 * CooL
 * Copyright (c) 2026 Northwind Cipher Pvt. Ltd.
 * SPDX-License-Identifier: BUSL-1.1
 *
 * Use of this software is governed by the Business Source License 1.1 in the
 * LICENSE file at the root of this repository.
 */

/**
 * Materialise a Contrast pod's `/contrast` directory from the fixture bundle.
 *
 * `tests/fixtures/contrast-fixtures.json` holds certificates and keys as base64
 * DER, generated by `tools/contrast-fixture` from Contrast's OWN `internal/ca`,
 * `internal/seedengine`, `internal/attestation/tdx` and `internal/oid`. This
 * helper writes them back out as the exact files Contrast's initializer creates,
 * into a temporary directory, so `ContrastWorkload.open({ root })` exercises the
 * real code path — including the PEM parsing and the file layout.
 *
 * Why the indirection rather than committing the PEM files: this repository
 * forbids committed `.pem` files and PEM private-key blocks
 * (`.github/workflows/security.yml`), and that is a rule worth keeping intact
 * rather than carving an exception into. Storing the same bytes as base64 DER in
 * a JSON file keeps the rule literal and keeps the fixtures' real value, which
 * is that Contrast's own code produced them.
 *
 * These keys are disposable and protect nothing. The TDX quote behind the
 * certificate claims was built in software: no confidential hardware was
 * involved in producing any of this.
 */
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const FIXTURE_FILE = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "fixtures",
  "contrast-fixtures.json",
);

interface WorkloadBundle {
  readonly certChainDer: readonly string[];
  readonly keyDer: string;
  readonly meshCaDer: readonly string[];
  readonly coordinatorRootDer: readonly string[];
  readonly workloadSecretHex?: string;
}

interface FixtureBundle {
  readonly coordinators: Readonly<
    Record<string, { readonly rootCaDer: readonly string[]; readonly meshCaDer: readonly string[] }>
  >;
  /** The Contrast `manifest.json`, verbatim, as text. */
  readonly manifest: string;
  readonly workloads: Readonly<Record<string, WorkloadBundle>>;
  readonly policyHashes: Readonly<Record<string, string>>;
  readonly measurements: Readonly<Record<string, string>>;
}

export const fixtures: FixtureBundle = JSON.parse(
  readFileSync(FIXTURE_FILE, "utf8"),
) as FixtureBundle;

/** The manifest bytes, for pinning. */
export const manifestBytes: Uint8Array = new TextEncoder().encode(fixtures.manifest);

/** Wrap base64 DER back into a PEM block, 64 characters to the line. */
function pem(label: string, der: string): string {
  const lines = [`-----BEGIN ${label}-----`];
  for (let i = 0; i < der.length; i += 64) lines.push(der.slice(i, i + 64));
  lines.push(`-----END ${label}-----`, "");
  return lines.join("\n");
}

function certificates(blocks: readonly string[]): string {
  return blocks.map((der) => pem("CERTIFICATE", der)).join("");
}

const roots: string[] = [];

/**
 * Write one fixture workload into a temporary directory, laid out exactly as
 * Contrast's initializer lays out `/contrast`, and return that path.
 */
export function contrastPod(name: string): string {
  const bundle = fixtures.workloads[name];
  if (!bundle) {
    throw new Error(
      `no fixture workload '${name}' (have: ${Object.keys(fixtures.workloads).sort().join(", ")})`,
    );
  }

  const root = mkdtempSync(join(tmpdir(), `cool-contrast-${name}-`));
  roots.push(root);

  const base = join(root, "contrast");
  mkdirSync(join(base, "tls-config"), { recursive: true });

  writeFileSync(join(base, "tls-config", "certChain.pem"), certificates(bundle.certChainDer));
  writeFileSync(join(base, "tls-config", "mesh-ca.pem"), certificates(bundle.meshCaDer));
  writeFileSync(
    join(base, "tls-config", "coordinator-root-ca.pem"),
    certificates(bundle.coordinatorRootDer),
  );
  writeFileSync(join(base, "tls-config", "key.pem"), pem("PRIVATE KEY", bundle.keyDer));

  // Omitted on purpose for `no-secret-service`: a pod whose manifest entry sets
  // no WorkloadSecretID gets no workload secret, and CooL must say so clearly.
  if (bundle.workloadSecretHex !== undefined) {
    mkdirSync(join(base, "secrets"), { recursive: true });
    writeFileSync(join(base, "secrets", "workload-secret-seed"), bundle.workloadSecretHex);
  }

  return base;
}

/** A Coordinator root CA, PEM — what `contrast verify` would write out. */
export function coordinatorRootCA(which: "genuine" | "rogue" = "genuine"): string {
  const coordinator = fixtures.coordinators[which];
  if (!coordinator) throw new Error(`no fixture coordinator '${which}'`);
  return certificates(coordinator.rootCaDer);
}

/** A path under the temporary tree, for the "not a Contrast pod" case. */
export function missingPod(): string {
  return join(mkdtempSync(join(tmpdir(), "cool-contrast-missing-")), "contrast");
}

/** Remove every directory this helper created. Call from an `after` hook. */
export function cleanupContrastPods(): void {
  for (const root of roots.splice(0)) {
    rmSync(root, { recursive: true, force: true });
  }
}
